language: generic
sudo: required
env:
  global:
    - TRAVIS=true
    - CODECOV_TOKEN="cb217982-9953-497d-bae4-2f183caf4385"
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - qemu-system-arm
script:
  - bash -c 'shopt -s globstar; shellcheck *.sh'